/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_provis;

import form.formJeniskendaraan;
import form.formKendaraan;
import form.formPelanggan;
import form.formSupir;
import form.formDetail;
import java.awt.Dimension;


/**
 *
 * @author Arvin Rizky
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JDesktopPane();
        btnsupir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnpelanggan = new javax.swing.JButton();
        btnjeniskendaraan = new javax.swing.JButton();
        btnkendaraan = new javax.swing.JButton();
        btnsupir1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mfile = new javax.swing.JMenu();
        medit = new javax.swing.JMenu();
        sbpelanggan = new javax.swing.JMenuItem();
        sbmember = new javax.swing.JMenuItem();
        mabout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelutama.setBackground(new java.awt.Color(102, 153, 255));

        btnsupir.setText("Data Supir");
        btnsupir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("RENTAL MOBIL BAGAS666");

        btnpelanggan.setText("Data Pelanggan");
        btnpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpelangganActionPerformed(evt);
            }
        });

        btnjeniskendaraan.setText("Jenis Kendaraan");
        btnjeniskendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjeniskendaraanActionPerformed(evt);
            }
        });

        btnkendaraan.setText("Data Kendaraan");
        btnkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkendaraanActionPerformed(evt);
            }
        });

        btnsupir1.setText("Sewa Kendaraan");
        btnsupir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupir1ActionPerformed(evt);
            }
        });

        panelutama.setLayer(btnsupir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelutama.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelutama.setLayer(btnpelanggan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelutama.setLayer(btnjeniskendaraan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelutama.setLayer(btnkendaraan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelutama.setLayer(btnsupir1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsupir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsupir1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnkendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnjeniskendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnjeniskendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsupir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnsupir1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        mfile.setText("File");
        jMenuBar1.add(mfile);

        medit.setText("Edit");

        sbpelanggan.setText("Data Pelanggan");
        sbpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbpelangganActionPerformed(evt);
            }
        });
        medit.add(sbpelanggan);

        sbmember.setText("Data Member");
        medit.add(sbmember);

        jMenuBar1.add(medit);

        mabout.setText("About");
        jMenuBar1.add(mabout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbpelangganActionPerformed
        // TODO add your handling code here:
       panelutama.removeAll();
       panelutama.repaint();
       formPelanggan plg = new formPelanggan();
       
       Dimension lutama = this.getSize();
       Dimension lplg = plg.getSize();
       
       plg.setLocation(lutama.width/2-lplg.width/2,lutama.height/2-lplg.height/2);
       panelutama.add(plg);
       plg.setVisible(true);
    }//GEN-LAST:event_sbpelangganActionPerformed

    private void btnpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpelangganActionPerformed
        // TODO add your handling code here:
       panelutama.removeAll();
       panelutama.repaint();
       formPelanggan plg = new formPelanggan();
       
       Dimension lutama = this.getSize();
       Dimension lplg = plg.getSize();
       
       plg.setLocation(lutama.width/2-lplg.width/2,lutama.height/2-lplg.height/2);
       panelutama.add(plg);
       plg.setVisible(true);
    }//GEN-LAST:event_btnpelangganActionPerformed

    private void btnsupirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupirActionPerformed
        // TODO add your handling code here:
       panelutama.removeAll();
       panelutama.repaint();
       formSupir spr = new formSupir();
       
       Dimension lutama = this.getSize();
       Dimension lspr = spr.getSize();
       
       spr.setLocation(lutama.width/2-lspr.width/2,lutama.height/2-lspr.height/2);
       panelutama.add(spr);
       spr.setVisible(true);
    }//GEN-LAST:event_btnsupirActionPerformed

    private void btnjeniskendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjeniskendaraanActionPerformed
        // TODO add your handling code here:
       panelutama.removeAll();
       panelutama.repaint();
       formJeniskendaraan jk = new formJeniskendaraan();
       
       Dimension lutama = this.getSize();
       Dimension ljk = jk.getSize();
       
       jk.setLocation(lutama.width/2-ljk.width/2,lutama.height/2-ljk.height/2);
       panelutama.add(jk);
       jk.setVisible(true);
    }//GEN-LAST:event_btnjeniskendaraanActionPerformed

    private void btnkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkendaraanActionPerformed
        // TODO add your handling code here:
        panelutama.removeAll();
        panelutama.repaint();
        formKendaraan kdr = new formKendaraan();
       
        Dimension lutama = this.getSize();
        Dimension lkdr = kdr.getSize();
       
        kdr.setLocation(lutama.width/2-lkdr.width/2,lutama.height/2-lkdr.height/2);
        panelutama.add(kdr);
        kdr.setVisible(true);
    }//GEN-LAST:event_btnkendaraanActionPerformed

    private void btnsupir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupir1ActionPerformed
        // TODO add your handling code here:
         panelutama.removeAll();
        panelutama.repaint();
        formDetail kdr = new formDetail();
       
        Dimension lutama = this.getSize();
        Dimension lkdr = kdr.getSize();
       
        kdr.setLocation(lutama.width/2-lkdr.width/2,lutama.height/2-lkdr.height/2);
        panelutama.add(kdr);
        kdr.setVisible(true);
    }//GEN-LAST:event_btnsupir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjeniskendaraan;
    private javax.swing.JButton btnkendaraan;
    private javax.swing.JButton btnpelanggan;
    private javax.swing.JButton btnsupir;
    private javax.swing.JButton btnsupir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mabout;
    private javax.swing.JMenu medit;
    private javax.swing.JMenu mfile;
    private javax.swing.JDesktopPane panelutama;
    private javax.swing.JMenuItem sbmember;
    private javax.swing.JMenuItem sbpelanggan;
    // End of variables declaration//GEN-END:variables
}
